<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="NBWenderson" name="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura" tests="5" failures="0" timestamp="28 Apr 2016 23:38:48 GMT" time="0.000" errors="5">
  <testcase name="testeCalcularConversorTemperatura" time="0.000" classname="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura">
    <error type="org.testng.TestNGException" message="
Parameter &#039;entradaParametro&#039; is required by @Test on method testeCalcularConversorTemperatura but has not been marked @Optional or defined
in C:\Users\Wenderson\AppData\Local\Temp\testng-eclipse--1352805289\testng-customsuite.xml">
      <![CDATA[org.testng.TestNGException: 
Parameter 'entradaParametro' is required by @Test on method testeCalcularConversorTemperatura but has not been marked @Optional or defined
in C:\Users\Wenderson\AppData\Local\Temp\testng-eclipse--1352805289\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1274)
	at org.testng.internal.Invoker.createParameters(Invoker.java:989)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1079)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testeCalcularConversorTemperatura -->
  <testcase name="testeCelsiusParaCelsius" time="0.000" classname="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura">
    <error type="java.lang.Throwable" message="Method ClsTestaPaginaDeConversorDeTemperatura.testeCelsiusParaCelsius()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ClsTestaPaginaDeConversorDeTemperatura.testeCelsiusParaCelsius()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testeCelsiusParaCelsius -->
  <testcase name="testeFahrenheitParaCelsius" time="0.000" classname="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura">
    <error type="java.lang.Throwable" message="Method ClsTestaPaginaDeConversorDeTemperatura.testeFahrenheitParaCelsius()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ClsTestaPaginaDeConversorDeTemperatura.testeFahrenheitParaCelsius()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testeFahrenheitParaCelsius -->
  <testcase name="testeFahrenheitParafahrenheit" time="0.000" classname="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura">
    <error type="java.lang.Throwable" message="Method ClsTestaPaginaDeConversorDeTemperatura.testeFahrenheitParafahrenheit()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ClsTestaPaginaDeConversorDeTemperatura.testeFahrenheitParafahrenheit()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testeFahrenheitParafahrenheit -->
  <testcase name="testeCelsiusParaFahrenheit" time="0.000" classname="br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura">
    <error type="java.lang.Throwable" message="Method ClsTestaPaginaDeConversorDeTemperatura.testeCelsiusParaFahrenheit()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods">
      <![CDATA[java.lang.Throwable: Method ClsTestaPaginaDeConversorDeTemperatura.testeCelsiusParaFahrenheit()[pri:0, instance:br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura@17e2f02] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1037)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
    </error>
  </testcase> <!-- testeCelsiusParaFahrenheit -->
</testsuite> <!-- br.com.seleniumgridewebdrivertestcase.ClsTestaPaginaDeConversorDeTemperatura -->
